
testing:
    build: .
    dockerfile: Dockerfile-Testing
    container_name: easysoap_test
    volumes:
    - ./index.js:/easysoap/index.js
    - ./package.json:/easysoap/package.json
    - ./__tests__:/easysoap/__tests__
    - ./lib:/easysoap/lib
